version: '3.8'

services:

  front:
    build: ./material-ui-nextjs-ts
    ports:
      - "3000:3000"
    volumes:
      - ./material-ui-nextjs-ts:/application

  bonds:
    build: ./bonds_service
    ports:
      - "5555:5000"
    environment:
      DATABASE_USER: james
      DATABASE_PASSWORD: double0seven
      DATABASE_NAME: bonds
      DATABASE_HOST: db

  db:
    build: ./database
    container_name: my_postgres
    environment:
      POSTGRES_USER: james
      POSTGRES_PASSWORD: double0seven
      POSTGRES_DB: bonds
    ports:
      - "5432:5432"
    volumes:
      - /Users/piotr/postgres/bonds:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "bonds", "-U", "james" ]
      timeout: 5s
      interval: 2s
      retries: 3
  
  liquibase:
    image: liquibase/liquibase:latest
    container_name: liquibase
    volumes:
      - ./database/liquibase/changelog:/liquibase/changelog
    command: '--driver=org.postgresql.Driver --url="jdbc:postgresql://db:5432/bonds" --changeLogFile=changelog/changelog_master.xml --username=james --password=double0seven update'
    depends_on:
      - db
  
      